version: '2'
services:
  vibeville-user-registration:
    depends_on:
      - "rabbitmq"
    image: tmokhele/vibevillerabbit
    ports:
    - "80:8080"
    stdin_open: true
    tty: true
    labels:
      io.rancher.container.pull_image: always
      id: vibevillerabbit
  rabbitmq:
    image: rabbitmq:3-management
    ports:
    - 15672:15672/tcp
    - 5672:5672/tcp
    labels:
      id: rabbitmq
      io.rancher.container.pull_image: always

