version: '2'
services:
  vibevillerabbit:
    depends_on:
      - "rabbitmq"
    image: tmokhele/vibevillerabbit
    hostname: vibevillerabbit
    ports:
    - "80:8080"
    stdin_open: true
    tty: true
    labels:
      io.rancher.scheduler.affinity:host_label_ne: sys=lb
      id: vibevillerabbit
      app: vibevillerabbit
  rabbitmq:
    image: rabbitmq:3-management
    ports:
    - 15672:15672/tcp
    - 5672:5672/tcp
    labels:
      id: rabbitmq
      app: rabbitmq
      io.rancher.scheduler.affinity:host_label_ne: sys=lb

