version: '2'
services:
  vibeville-user-registration:
    image: tmokhele/vibevillerabbit
    ports:
    - "80:8080"
    stdin_open: true
    tty: true
    labels:
      io.rancher.container.pull_image: always
      id: vibevillerabbit

